### ISSUE TITLE
Landing page (section 3): About Cloud Native Nordics

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#30]
Landing page overview: 
![landing-mockup](https://user-images.githubusercontent.com/4429108/67224353-49c91300-f431-11e9-891e-2fad5de41d20.png)

This issue focuses on section 3, a short description of Cloud Native Nordics. The what, how, and why?

*Title:* Building and scaling the adoption of Cloud Native in the nordics

We need some input and ideas for the description.

The definition of done for this issue, includes writing the description, but also make sure that this section handles mobile layouts as well.

**Comment by kaspernissen** [comment]
/cc @luxas @Solisol @netumoliver @Steiniche @hoeghh @jepp2078 
Ideas for this?

**Comment by Steiniche** [comment]
Quick brainstorm.

I think it should focus on why we have started this community.

- It gives us the opportunity to provide better speakers and meetups
- We can help each other developing the "meetup kit" in an open source fashion
- We do everything open source because we believe in it
- We want to democratize the knowledge about Cloud Native, what it means and what benefits it bring

Why is it only for the nordic contries / why are we a nordic community?

Should this section also contain that we are a community of official CNCF meetups?

This section could contain an image from a meetup, of the organizers, Cloud Native Con barcelona where everybody is wearing the shirt.

**Comment by kaspernissen** [comment]
I've updated the page with some of this stuff. Let's create a new issue if we want to change what we have now :)
